###Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
import time

In [ ]:
#1
empty_array= np.empty((2, 2))
print(empty_array)

[[1.43301161e-315 0.00000000e+000]
 [6.70417282e-310 6.70418406e-310]]


In [ ]:
#2
ones_array = np.ones((4, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#3
full_array = np.full((3, 3), 7)
print(full_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#4
l = np.array([[1, 2], [3, 4]])
arr_zeros_like = np.zeros_like(l)
print(arr_zeros_like)

[[0 0]
 [0 0]]


In [ ]:
#5
arr_ones_like = np.ones_like(l)
print(arr_ones_like)

[[1 1]
 [1 1]]


In [ ]:
#6
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print(arr_from_list)

[1 2 3 4]


####Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
#1
arr1 = np.arange(10, 50)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#2
arr2 = np.arange(9).reshape(3, 3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#3
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#4
arr_random = np.random.random(30)
mean_value = arr_random.mean()

print("Array:", arr_random)
print("Mean:", mean_value)

Array: [0.80763866 0.45249451 0.83584693 0.67088078 0.26426324 0.23773275
 0.63381971 0.3894826  0.33433565 0.93874729 0.77172195 0.97819876
 0.9225182  0.35721459 0.83288296 0.81040798 0.01124809 0.62043589
 0.29197602 0.99281719 0.09785122 0.81026683 0.15463854 0.95108577
 0.03610739 0.84869364 0.8727967  0.74142511 0.29073352 0.87157149]
Mean: 0.5943277980986088


In [ ]:
#5
arr_rand_10 = np.random.random((10, 10))
min_value = arr_rand_10.min()
max_value = arr_rand_10.max()

print("Min:", min_value)
print("Max:", max_value)

Min: 0.011216228779307502
Max: 0.9992100620910747


In [ ]:
#6
arr_zero = np.zeros(10)
arr_zero[4] = 1
print(arr_zero)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]

print(reversed_arr)

[0 4 0 0 2 1]


In [ ]:
#8
arr_border = np.ones((5, 5))
arr_border[1:-1, 1:-1] = 0

print(arr_border)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#9
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


####Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
x = np.array([[1, 2],[3, 5]])
y = np.array([[5, 6],[7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [ ]:
#1
add_xy = x + y
print(add_xy)

[[ 6  8]
 [10 13]]


In [ ]:
#2
sub_xy = x - y
print(sub_xy)

[[-4 -4]
 [-4 -3]]


In [ ]:
#3
mul_x = x * 3
print(mul_x)

[[ 3  6]
 [ 9 15]]


In [ ]:
#4
square_x = x ** 2
print(square_x)

[[ 1  4]
 [ 9 25]]


In [ ]:
#5
#5.1
dot_vw = np.dot(v, w)
print(dot_vw)

219


In [ ]:
#5.2
dot_xv = np.dot(x, v)
print(dot_xv)

[29 77]


In [ ]:
#5.3
dot_xy = np.dot(x, y)
print(dot_xy)

[[19 22]
 [50 58]]


In [ ]:
#6
#6.1
concat_rows = np.concatenate((x, y), axis=0)
print(concat_rows)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [ ]:
#6.1
concat_rows = np.vstack((x, y))
print(concat_rows)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [ ]:
#6.2
vw_column = np.column_stack((v, w))
print(vw_column)

[[ 9 11]
 [10 12]]


In [69]:
#7
np.concatenate((x, v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

#####Because the number of dimensions is different. i.e. x is 2D → shape (2, 2) v is 1D → shape (2,)

###Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = BTAT.

• Solve the following system of Linear equation using Inverse Methods.

                    2x − 3y + z = −1

                    x − y + 2z = −3

                    3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
#Part1
A = np.array([[3, 4],[7, 8]])

B = np.array([[5, 3],[2, 1]])

In [ ]:
#1
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
result_rounded = np.round(result, decimals=10)
print(result_rounded)

In [ ]:
#2
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)

In [ ]:
#3
left = np.transpose(np.dot(A, B))
right = np.dot(np.transpose(B), np.transpose(A))
print(left)
print(right)

###Part 2
2x − 3y +  z = −1

 x −  y + 2z = −3

3x +  y −  z = 9


In [70]:
A = np.array([
    [2, -3,  1],
    [1, -1,  2],
    [3,  1, -1]
])

In [71]:
B = np.array([-1, -3, 9])

In [72]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution:", X)

Solution: [ 2.  1. -2.]


In [73]:
#Part3
X = np.linalg.solve(A, B)
print("Solution:", X)

Solution: [ 2.  1. -2.]


####4.2
####1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [74]:
# Create two lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

# Start time
start_time = time.time()

# Element-wise addition using list comprehension
result_list = [a + b for a, b in zip(list1, list2)]

# End time
end_time = time.time()

print("Time taken using Python lists:", end_time - start_time, "seconds")

Time taken using Python lists: 0.08629655838012695 seconds


In [75]:
# Create two NumPy arrays of size 1,000,000
arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

# Start time
start_time = time.time()

# Element-wise addition using NumPy
result_array = arr1 + arr2

# End time
end_time = time.time()

print("Time taken using NumPy arrays:", end_time - start_time, "seconds")


Time taken using NumPy arrays: 0.004038572311401367 seconds


####2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [76]:
# Create two lists of size 1,000,000
list1 = list(range(1, 1000001))
list2 = list(range(1, 1000001))

# Start timer
start_time = time.time()

# Element-wise multiplication using list comprehension
result_list = [a * b for a, b in zip(list1, list2)]

# End timer
end_time = time.time()

print("Time taken using Python lists:", end_time - start_time, "seconds")


Time taken using Python lists: 0.07811641693115234 seconds


In [77]:
# Create two NumPy arrays of size 1,000,000
arr1 = np.arange(1, 1000001)
arr2 = np.arange(1, 1000001)

# Start timer
start_time = time.time()

# Element-wise multiplication using NumPy
result_array = arr1 * arr2

# End timer
end_time = time.time()

print("Time taken using NumPy arrays:", end_time - start_time, "seconds")


Time taken using NumPy arrays: 0.004507303237915039 seconds


####3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [78]:
# Create two lists of size 1,000,000
list1 = list(range(1, 1000001))
list2 = list(range(1, 1000001))

# Start timer
start_time = time.time()

# Dot product using a loop or sum of element-wise multiplication
dot_product = sum(a * b for a, b in zip(list1, list2))

# End timer
end_time = time.time()

print("Dot product using Python lists:", dot_product)
print("Time taken using Python lists:", end_time - start_time, "seconds")


Dot product using Python lists: 333333833333500000
Time taken using Python lists: 0.08450722694396973 seconds


In [79]:
# Create two NumPy arrays
arr1 = np.arange(1, 1000001)
arr2 = np.arange(1, 1000001)

# Start timer
start_time = time.time()

# Dot product using NumPy
dot_product_np = np.dot(arr1, arr2)

# End timer
end_time = time.time()

print("Dot product using NumPy arrays:", dot_product_np)
print("Time taken using NumPy arrays:", end_time - start_time, "seconds")


Dot product using NumPy arrays: 333333833333500000
Time taken using NumPy arrays: 0.002277851104736328 seconds


####4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [83]:
import random
# Create two 1000x1000 matrices using Python lists
size = 1000
matrix1 = [[random.randint(1, 10) for _ in range(size)] for _ in range(size)]
matrix2 = [[random.randint(1, 10) for _ in range(size)] for _ in range(size)]
# Start timer
start_time = time.time()
# Initialize result matrix with zeros
result = [[0 for _ in range(size)] for _ in range(size)]
# Matrix multiplication using nested loops
for i in range(size):
    for j in range(size):
        for k in range(size):
            result[i][j] += matrix1[i][k] * matrix2[k][j]
# End timer
end_time = time.time()
print("Time taken using Python lists:", end_time - start_time, "seconds")

Time taken using Python lists: 279.06153178215027 seconds


In [80]:
# Create two 1000x1000 matrices
matrix1_np = np.random.randint(1, 10, size=(1000, 1000))
matrix2_np = np.random.randint(1, 10, size=(1000, 1000))

# Start timer
start_time = time.time()

# Matrix multiplication using NumPy
result_np = np.dot(matrix1_np, matrix2_np)
# Or you can use: result_np = matrix1_np @ matrix2_np

# End timer
end_time = time.time()

print("Time taken using NumPy arrays:", end_time - start_time, "seconds")


Time taken using NumPy arrays: 2.6451377868652344 seconds
